basePath: /
host: 127.0.0.1:8080
info:
  contact: {}
  description: 使用Go、Gin、Elasticsearch开发的一个网易云音乐歌曲、评论搜索API，可以在web上点击发请求哦，能查到数据，不过当然不是全部的数据啦
  license: {}
  title: 云音乐歌曲、评论搜索API
  version: "1.0"
paths:
  /api/comments:
    get:
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        required: true
        type: integer
      - description: 歌曲ID
        in: query
        name: song_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":""}'
          schema:
            type: string
      summary: 根据歌曲ID获取评论列表
  /api/hot_comments:
    get:
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":""}'
          schema:
            type: string
      summary: 热门评论，按点赞数排行
  /api/hot_songs:
    get:
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":""}'
          schema:
            type: string
      summary: 获取热门歌曲，按评论数排行
  /api/search/artists:
    get:
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        required: true
        type: integer
      - description: 关键词
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":""}'
          schema:
            type: string
      summary: 搜索歌手
  /api/search/comments:
    get:
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        required: true
        type: integer
      - description: 关键词
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":""}'
          schema:
            type: string
      summary: 按关键词搜索评论
  /api/search/songs:
    get:
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        required: true
        type: integer
      - description: 关键词
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":""}'
          schema:
            type: string
      summary: 按关键词搜索歌曲
  /api/songs:
    get:
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        required: true
        type: integer
      - description: 歌手ID
        in: query
        name: artist_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":""}'
          schema:
            type: string
      summary: 根据歌手ID获取歌曲列表
swagger: "2.0"
